[package]
name = "diesel-repository-trait"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true, optional = true }
diesel = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }


[features]
default = []
async = ["async-trait"]
