[package]
name = "diesel-repository-test-sync"
edition = "2021"
publish = false
version = "0.1.0"

[workspace]

[dependencies]
diesel-repository = { path = "../../packages/diesel-repository", features = ["sync"] }
diesel = { version = "2.0" }
anyhow = { version = "1.0" }