[package]
name = "diesel-repository-macro"
edition = "2021"
version.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
proc-macro-error2 = { workspace = true }

diesel-repository-macro-core = { workspace = true }
diesel-repository-macro-sync = { workspace = true }
diesel-repository-macro-async = { workspace = true, optional = true }

[features]
async = ["diesel-repository-macro-async"]
