[package]
name = "diesel-repository-macro-sync"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
diesel-repository-macro-core = { workspace = true }
proc-macro-error2 = { workspace = true }

