[package]
name = "diesel-repository"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
diesel-repository-macro = { workspace = true }
diesel-repository-trait = { workspace = true }

[features]
async = ["diesel-repository-trait/async", "diesel-repository-macro/async"]
